import 'package:basic_flutter/data_class/dataclass.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class Test04 extends StatefulWidget {
  final Autogenerated h2;
  const Test04({Key? key, required this.h2}) : super(key: key);

  @override
  State<Test04> createState() => _Test04State();
}

class _Test04State extends State<Test04> {
  late Autogenerated h2;
  @override
  void initState() {
    super.initState();
    h2 = widget.h2;
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            Text(h2.id.toString()),
            Text(h2.title),
            Text(h2.completed.toString()),
            Text(h2.userId.toString()),
          ],)),
    );
  }
}
