import 'package:basic_flutter/data_class/dataclass.dart';
import 'package:basic_flutter/test4.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'dart:math';

class Test03 extends StatefulWidget {
  const Test03({Key? key}) : super(key: key);

  @override
  State<Test03> createState() => _Test03State();
}

class _Test03State extends State<Test03> {
  List<Autogenerated> b = [];

  ///System Volume Information
  List<Widget> widgets = [];
  List colors1 = [Colors.red, Colors.green, Colors.yellow];
  Random random = new Random();

  int index = 0;
  int numbercolor = 6;

  void changeIndex() {
    setState(() => index = random.nextInt(3));

    if (numbercolor == index) changeIndex();
    numbercolor = index;
  }

  @override
  void initState() {
    super.initState();
    readdata();
  }

  Future<void> readdata() async {
    String url = "https://jsonplaceholder.typicode.com/todos/";
    Response response = await Dio().get(url);
    int indexs = 0;
    for (var sna in response.data) {
      Map<String, dynamic> map = sna;
      Autogenerated model = Autogenerated.fromMap(map);
      setState(
        () {
          changeIndex();
          b.add(model);
          widgets.add(createWidget(model, indexs));
        },
      );
      indexs++;
    }
  }

  Widget createWidget(var h2, int index) => GestureDetector(
        child: Card(
          child: Center(
            child: Column(
              children: [
                ListTile(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => Test04(
                            h2: b[index],
                          ),
                        ),
                      );
                    },
                    leading: const Icon(Icons.car_rental),
                    title: Text(h2["province"]),
                    subtitle: Text(h2["new_case"].toString()),
                    tileColor: colors1[index]),
              ],
            ),
          ),
        ),
      );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: RadialGradient(
            center: Alignment(0, -0.33),
            radius: 2,
            colors: <Color>[Colors.white, Colors.blue],
          ),
        ),
        child: widgets.isEmpty
            ? const Center(child: CircularProgressIndicator())
            : ListView(children: widgets),
      ),
    );
  }
}
